import { Tool, ToolResult } from './types';

/**
 * Calendar Service - Google Calendar Integration
 *
 * Setup:
 * 1. Create Google Cloud Project
 * 2. Enable Google Calendar API
 * 3. Create OAuth 2.0 credentials
 * 4. Add to .env:
 *    - GOOGLE_CLIENT_ID
 *    - GOOGLE_CLIENT_SECRET
 *    - GOOGLE_REFRESH_TOKEN (obtained via OAuth flow)
 */

interface CalendarEvent {
  id: string;
  summary: string;
  description?: string;
  start: { dateTime: string; timeZone?: string };
  end: { dateTime: string; timeZone?: string };
  location?: string;
  attendees?: Array<{ email: string }>;
}

export const searchCalendarTool: Tool = {
  name: 'search_calendar',
  description: 'Search Google Calendar for events, meetings, and appointments. Can find events by date range, keywords, or attendees.',
  parameters: {
    query: {
      type: 'string',
      description: 'Search query (e.g., "team meeting", "dentist appointment")',
      required: false,
    },
    timeMin: {
      type: 'string',
      description: 'Start date/time (ISO 8601 format, e.g., "2024-01-15T00:00:00Z")',
      required: false,
    },
    timeMax: {
      type: 'string',
      description: 'End date/time (ISO 8601 format)',
      required: false,
    },
    maxResults: {
      type: 'number',
      description: 'Maximum number of events to return (1-50)',
      required: false,
      default: 10,
    },
  },
  execute: async (params: Record<string, unknown>): Promise<ToolResult> => {
    const { query, timeMin, timeMax, maxResults = 10 } = params;

    try {
      if (!process.env.GOOGLE_REFRESH_TOKEN) {
        return {
          success: false,
          error: 'Google Calendar not configured. Add GOOGLE_CLIENT_ID, GOOGLE_CLIENT_SECRET, and GOOGLE_REFRESH_TOKEN to .env',
        };
      }

      const accessToken = await getGoogleAccessToken();
      const events = await fetchCalendarEvents(
        accessToken,
        query as string | undefined,
        timeMin as string | undefined,
        timeMax as string | undefined,
        maxResults as number
      );

      return {
        success: true,
        data: {
          events,
          count: events.length,
        },
        metadata: {
          timestamp: Date.now(),
        },
      };
    } catch (error) {
      return {
        success: false,
        error: error instanceof Error ? error.message : 'Calendar search failed',
      };
    }
  },
};

export const createCalendarEventTool: Tool = {
  name: 'create_calendar_event',
  description: 'Create a new event in Google Calendar',
  parameters: {
    summary: {
      type: 'string',
      description: 'Event title/summary',
      required: true,
    },
    start: {
      type: 'string',
      description: 'Start date/time (ISO 8601 format)',
      required: true,
    },
    end: {
      type: 'string',
      description: 'End date/time (ISO 8601 format)',
      required: true,
    },
    description: {
      type: 'string',
      description: 'Event description',
      required: false,
    },
    location: {
      type: 'string',
      description: 'Event location',
      required: false,
    },
    attendees: {
      type: 'array',
      description: 'Array of attendee email addresses',
      required: false,
    },
  },
  execute: async (params: Record<string, unknown>): Promise<ToolResult> => {
    const { summary, start, end, description, location, attendees } = params;

    try {
      const accessToken = await getGoogleAccessToken();

      const event: CalendarEvent = {
        id: '', // Will be generated by Google
        summary: summary as string,
        start: { dateTime: start as string },
        end: { dateTime: end as string },
        description: description as string | undefined,
        location: location as string | undefined,
        attendees: (attendees as string[])?.map((email) => ({ email })),
      };

      const response = await fetch(
        'https://www.googleapis.com/calendar/v3/calendars/primary/events',
        {
          method: 'POST',
          headers: {
            'Authorization': `Bearer ${accessToken}`,
            'Content-Type': 'application/json',
          },
          body: JSON.stringify(event),
        }
      );

      if (!response.ok) {
        const error = await response.json();
        throw new Error(`Calendar API error: ${error.error?.message || response.statusText}`);
      }

      const createdEvent = await response.json();

      return {
        success: true,
        data: {
          event: createdEvent,
          eventLink: createdEvent.htmlLink,
        },
        metadata: {
          timestamp: Date.now(),
        },
      };
    } catch (error) {
      return {
        success: false,
        error: error instanceof Error ? error.message : 'Failed to create event',
      };
    }
  },
};

// Helper: Get Google Access Token using Refresh Token
async function getGoogleAccessToken(): Promise<string> {
  const response = await fetch('https://oauth2.googleapis.com/token', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/x-www-form-urlencoded',
    },
    body: new URLSearchParams({
      client_id: process.env.GOOGLE_CLIENT_ID!,
      client_secret: process.env.GOOGLE_CLIENT_SECRET!,
      refresh_token: process.env.GOOGLE_REFRESH_TOKEN!,
      grant_type: 'refresh_token',
    }),
  });

  if (!response.ok) {
    throw new Error('Failed to refresh Google access token');
  }

  const data = await response.json();
  return data.access_token;
}

// Helper: Fetch Calendar Events
async function fetchCalendarEvents(
  accessToken: string,
  query?: string,
  timeMin?: string,
  timeMax?: string,
  maxResults = 10
): Promise<CalendarEvent[]> {
  const params = new URLSearchParams({
    maxResults: maxResults.toString(),
    orderBy: 'startTime',
    singleEvents: 'true',
  });

  if (query) params.append('q', query);
  if (timeMin) params.append('timeMin', timeMin);
  if (timeMax) params.append('timeMax', timeMax);

  const response = await fetch(
    `https://www.googleapis.com/calendar/v3/calendars/primary/events?${params}`,
    {
      headers: {
        'Authorization': `Bearer ${accessToken}`,
      },
    }
  );

  if (!response.ok) {
    const error = await response.json();
    throw new Error(`Calendar API error: ${error.error?.message || response.statusText}`);
  }

  const data = await response.json();
  return data.items || [];
}
